# Generated by Django 5.2.14 on 2026-05-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
    ]
